# Generated by Django 3.2.5 on 2023-07-18 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='api.contributor'),
        ),
    ]
