# Generated by Django 4.2.2 on 2023-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('B', 'Bug'), ('T', 'Task'), ('S', 'STORY')], max_length=50),
        ),
    ]
