# Generated by Django 4.2.2 on 2023-07-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('B', 'BACKEND'), ('F', 'FRONTEND'), ('I', 'IOS'), ('A', 'Android')], default='B', max_length=9),
        ),
    ]
