# Generated by Django 4.2.2 on 2023-07-18 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('T', 'TODO'), ('I', 'IN PROGRESS'), ('F', 'FINISHED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('B', 'Bug'), ('T', 'TASK'), ('F', 'FEATURE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('B', 'BACKEND'), ('F', 'FRONTEND'), ('I', 'IOS'), ('A', 'Android')], default='', max_length=9),
        ),
    ]
